<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="environment.props" Condition="Exists('environment.props')" />

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BEPINEX_PATH)/core/BepInEx.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BEPINEX_PATH)/core/0Harmony.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>$(VALHEIM_MANAGED)/publicized_assemblies/assembly_valheim_publicized.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(VALHEIM_MANAGED)/publicized_assemblies/assembly_utils_publicized.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.CoreModule.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.PhysicsModule.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.InputLegacyModule.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(VALHEIM_MANAGED)/UnityEngine.UI.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(VALHEIM_MANAGED)/Unity.TextMeshPro.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Package\plugins\**" />
    <EmbeddedResource Remove="Package\plugins\**" />
    <None Remove="Package\plugins\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Package\icon.png" />
  </ItemGroup>
</Project>
